// Builds one review sheet per data file: review/<set>.md, our Mongolian next to KANJIDIC2 readings.
// Also validates every data file. Usage: node ja-mn/tools/build-review.js
const fs = require('fs');
const path = require('path');
const { root, kanjidic, kradfile, fileSets } = require('./lib-sources');

const ref = kanjidic();
const parts = kradfile();
const sets = fileSets(ref);
const KINDS = ['', 'origin', 'mnemonic', 'compare', 'usage'];
const cell = (s) => String(s).replace(/\|/g, '\\|');

const dir = path.join(root, 'kanji');
const seen = new Set();
let total = 0;
let problems = 0;
fs.mkdirSync(path.join(root, 'review'), { recursive: true });

for (const file of fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort()) {
  const set = file.replace('.json', '');
  const entries = JSON.parse(fs.readFileSync(path.join(dir, file), 'utf8'));
  for (const e of entries) {
    const warn = (msg) => { problems++; console.log(`${file} ${e.kanji}: ${msg}`); };
    if (seen.has(e.kanji)) warn('duplicate');
    seen.add(e.kanji);
    if (!sets[set] || !sets[set].includes(e.kanji)) warn(`not in set ${set}`);
    if (!KINDS.includes(e.note_kind)) warn(`bad note_kind ${e.note_kind}`);
    if (e.note_mn && !e.note_kind) warn('note without note_kind');
    if (!e.meanings_mn.length) warn('no meanings');
    for (const x of e.examples) if (!x.word.includes(e.kanji)) warn(`example ${x.word} lacks the kanji`);
    // Mongolian text must be Cyrillic: catch Latin look-alikes (x, o, e…) and stray accented letters.
    const mn = [...e.meanings_mn, e.note_mn, ...e.examples.map((x) => x.mn)].join(' ');
    if (/[A-Za-zÀ-ɏ]/.test(mn)) warn(`Latin letter in Mongolian text: ${mn.match(/\S*[A-Za-zÀ-ɏ]\S*/)[0]}`);
  }
  total += entries.length;

  const rows = entries.map((e, i) => {
    const r = ref[e.kanji] || { on: [], kun: [], en: [] };
    const ex = e.examples.map((x) => `${x.word}（${x.reading}）${x.mn}`).join('<br>');
    const icon = { origin: '📜 ', mnemonic: '💡 ', compare: '🇲🇳 ', usage: '📝 ' }[e.note_kind] || '';
    return `| ${i + 1} | **${e.kanji}** | ${r.on.slice(0, 3).join('、')} / ${r.kun.slice(0, 3).join('、')} | ${cell(r.en.slice(0, 3).join('; '))} | ${cell(e.meanings_mn.join('; '))} | ${(parts[e.kanji] || []).join(' ')} | ${cell(icon + e.note_mn)} | ${cell(ex)} | ${e.status === 'reviewed' ? '☑' : '☐'} |`;
  });
  fs.writeFileSync(path.join(root, `review/${set}.md`), `# Review: ${set} (${entries.length} / ${(sets[set] || []).length})

Generated by \`ja-mn/tools/build-review.js\` — fix \`ja-mn/kanji/${file}\`, not this sheet.

📜 origin · 💡 memory aid (not etymology) · 🇲🇳 Japanese↔Mongolian contrast · 📝 usage tip

| # | Kanji | On / Kun | English (KANJIDIC2) | Монгол утга | Parts | Тайлбар | Жишээ | OK |
|---|-------|----------|---------------------|-------------|-------|---------|-------|----|
${rows.join('\n')}
`);
}
// Words: ja-mn/words/<range>.json → review/words-<range>.md
const POS = ['noun', 'pronoun', 'verb', 'adj-i', 'adj-na', 'adverb', 'particle', 'auxiliary', 'conjunction',
  'interjection', 'prenoun', 'prefix', 'suffix', 'counter', 'expression'];
const INFLECTS = ['verb', 'adj-i', 'auxiliary'];
const wdir = path.join(root, 'words');
const wseen = new Map();
let words = 0;
for (const file of fs.existsSync(wdir) ? fs.readdirSync(wdir).filter((f) => f.endsWith('.json')).sort() : []) {
  const entries = JSON.parse(fs.readFileSync(path.join(wdir, file), 'utf8'));
  for (const e of entries) {
    const warn = (msg) => { problems++; console.log(`words/${file} ${e.word}: ${msg}`); };
    const key = `${e.word}|${e.pos}`;
    if (wseen.has(key)) warn('duplicate');
    wseen.set(key, file);
    if (!POS.includes(e.pos)) warn(`bad pos ${e.pos}`);
    if (!KINDS.includes(e.note_kind)) warn(`bad note_kind ${e.note_kind}`);
    if (e.note_mn && !e.note_kind) warn('note without note_kind');
    if (!e.meanings_mn.length) warn('no meanings');
    if (!/^[぀-ゟー]+$/.test(e.reading)) warn(`reading not hiragana: ${e.reading}`);
    // The example must show the word: as written, in an alternate spelling, or (if it inflects) by its stem.
    const forms = [e.word, ...e.alt];
    // Phrases ending in a verb or い-adjective (手に入れる, いい加減にする) inflect too: drop する, or the last kana.
    const inflects = INFLECTS.includes(e.pos) || (e.pos === 'expression' && /[うくぐすつぬぶむるい]$/.test(e.word));
    const stems = inflects ? forms.map((w) => w.replace(/する$|.$/, '')).filter(Boolean) : [];
    if (e.word === 'する') stems.push('し', 'さ', 'せ');
    if (![...forms, ...stems].some((w) => e.example.ja.includes(w))) warn(`example lacks the word: ${e.example.ja}`);
    const mn = [...e.meanings_mn, e.note_mn, e.example.mn].join(' ');
    if (/[A-Za-zÀ-ɏ]/.test(mn)) warn(`Latin letter in Mongolian text: ${mn.match(/\S*[A-Za-zÀ-ɏ]\S*/)[0]}`);
  }
  words += entries.length;
  const icon = { origin: '📜 ', mnemonic: '💡 ', compare: '🇲🇳 ', usage: '📝 ' };
  const rows = entries.map((e, i) => `| ${i + 1} | **${e.word}** | ${e.reading} | ${cell(e.alt.join('、'))} | ${e.pos} | ${cell(e.meanings_mn.join('; '))} | ${cell((icon[e.note_kind] || '') + e.note_mn)} | ${cell(e.example.ja)}<br>${cell(e.example.mn)} | ${e.status === 'reviewed' ? '☑' : '☐'} |`);
  const range = file.replace('.json', '');
  fs.writeFileSync(path.join(root, `review/words-${range}.md`), `# Review: words ${range} (${entries.length})

Generated by \`ja-mn/tools/build-review.js\` — fix \`ja-mn/words/${file}\`, not this sheet.

| # | Үг | Унших | Өөр бичлэг | Pos | Монгол утга | Тайлбар | Жишээ | OK |
|---|----|-------|-----------|-----|-------------|---------|-------|----|
${rows.join('\n')}
`);
}
console.log(`${total} kanji, ${words} words, ${problems} problems`);
process.exitCode = problems ? 1 : 0;
