// Merges data/kanji.json with KANJIDIC2 + KRADFILE (sources/) into review/kanji.md,
// a table a Mongolian speaker can check line by line.
// Usage: sh scripts/fetch-sources.sh && node scripts/build-review.js
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');

const xml = fs.readFileSync(path.join(root, 'sources/kanjidic2.xml'), 'utf8');
const ref = {};
for (const m of xml.matchAll(/<character>([\s\S]*?)<\/character>/g)) {
  const c = m[1];
  const all = (re) => [...c.matchAll(re)].map((x) => x[1]);
  ref[c.match(/<literal>(.*?)<\/literal>/)[1]] = {
    on: all(/<reading r_type="ja_on">(.*?)<\/reading>/g),
    kun: all(/<reading r_type="ja_kun">(.*?)<\/reading>/g),
    en: all(/<meaning>(.*?)<\/meaning>/g),
    strokes: +c.match(/<stroke_count>(\d+)/)[1],
  };
}

const krad = new TextDecoder('euc-jp').decode(fs.readFileSync(path.join(root, 'sources/kradfile')));
const parts = {};
for (const l of krad.split('\n')) {
  if (!l || l[0] === '#') continue;
  const [k, r] = l.split(' : ');
  if (r) parts[k.trim()] = r.trim().split(' ');
}

const entries = JSON.parse(fs.readFileSync(path.join(root, 'data/kanji.json'), 'utf8'));
const cell = (s) => String(s).replace(/\|/g, '\\|');
const rows = entries.map((e, i) => {
  const r = ref[e.kanji] || { on: [], kun: [], en: [], strokes: '' };
  const ex = e.examples.map((x) => `${x.word}（${x.reading}）${x.mn}`).join('<br>');
  const note = e.note_mn ? `${e.note_kind === 'mnemonic' ? '💡 ' : '📜 '}${e.note_mn}` : '';
  return `| ${i + 1} | **${e.kanji}** | ${r.on.slice(0, 3).join('、')} / ${r.kun.slice(0, 3).join('、')} | ${cell(r.en.slice(0, 3).join('; '))} | ${cell(e.meanings_mn.join('; '))} | ${(parts[e.kanji] || []).join(' ')} | ${cell(note)} | ${cell(ex)} | ☐ |`;
});

const out = `# Kanji review sheet

Generated by \`scripts/build-review.js\` — do not edit by hand; fix \`data/kanji.json\` instead.

📜 = established origin · 💡 = memory aid (not etymology). Tick ☐ → ☑ when the row is correct, or write the fix next to it.

| # | Kanji | On / Kun | English (KANJIDIC2) | Монгол утга | Parts | Тайлбар | Жишээ | OK |
|---|-------|----------|---------------------|-------------|-------|---------|-------|----|
${rows.join('\n')}
`;
fs.writeFileSync(path.join(root, 'review/kanji.md'), out);
console.log(`review/kanji.md: ${rows.length} rows`);
